### ISSUE TITLE
Can't initialize sys standard streams

### ISSUE THREAD

**Issue by fivann** [webcomics/pywine#17]
Hello team! I faced this error running Pywine as part of Jenkins pipeline with Docker agent:
=====
+ whoami
root
+ wine python -V
Python 3.10.4
+ wine pyinstaller -h
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
OSError: [WinError 6] Invalid handle

Current thread 0x000000d4 (most recent call first):
  <no Python frame>
=====
What I'm doing wrong?

**Comment by TobiX** [comment]
I think I had similar problem when running in Jenkins, try piping the stdout and stderr into a file (for example, appending `2>&1 | tee log.txt` to the line)

**Comment by fivann** [comment]
> I think I had similar problem when running in Jenkins, try piping the stdout and stderr into a file (for example, appending `2>&1 | tee log.txt` to the line)

Thank you! It works for me.
