### ISSUE TITLE
wine pip not working

### ISSUE THREAD

**Issue by ByVictorrr** [webcomics/pywine#18]
root@adf4361ceeaf:/opt/wineprefix/drive_c/iosp# wine pip
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

**Comment by ByVictorrr** [comment]
using pyinstaller: 

 Traceback (most recent call last):
#30 59.11   File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
#30 59.11     return _run_code(code, main_globals, None,
#30 59.11   File "C:\Python39\lib\runpy.py", line 87, in _run_code
#30 59.11     exec(code, run_globals)
#30 59.11   File "C:\Python39\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
#30 59.12   File "C:\Python39\lib\site-packages\PyInstaller\__main__.py", line 124, in run
#30 59.12     run_build(pyi_config, spec_file, **vars(args))
#30 59.12   File "C:\Python39\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
#30 59.12     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
#30 59.12   File "C:\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 803, in main
#30 59.12     build(specfile, distpath, workpath, clean_build)
#30 59.13   File "C:\Python39\lib\site-packages\PyInstaller\building\toc_conversion.py", line 51, in __init__
#30 59.13     self._distributions.update(self._get_distribution_for_node(node))
#30 59.13   File "C:\Python39\lib\site-packages\PyInstaller\building\toc_conversion.py", line 88, in _get_distribution_for_node
#30 59.13     assert len(dists) == 1
#30 59.13 AssertionError

**Comment by TobiX** [comment]
I cannot reproduce this problem.
```
root@f295eae1b6be:/# wine pip -V   
pip 22.0.4 from C:\Python39\lib\site-packages\pip (python 3.10)
```
