### ISSUE TITLE
How to use this container?

### ISSUE THREAD

**Issue by peerchemist** [webcomics/pywine#3]
I am not sure how to use this container? Care to explain?

My goal is to run pyinstaller on a python package and get a windows-compatible dist.

**Comment by TobiX** [comment]
For example like this:

https://github.com/webcomics/dosage/blob/39356bc468dd6179544b69e16b7a56828e78d4e4/Jenkinsfile#L101-L108

As explained in the parent [wine-staging](https://github.com/TobiX/wine-staging#docker-wine-staging) repository, you need to use xvfb-run to wrap calls to wine and probably wait for completion using `wineserver -w`
