### ISSUE TITLE
3.11 - No installed Python found!

### ISSUE THREAD

**Issue by marcelomanzo** [webcomics/pywine#33]
I am trying to move my CI gitlab from the pywine3.10 to pywine3.11, when using the 3.11 docker image, I get the following error message:
![image](https://user-images.githubusercontent.com/12878783/208789604-20ae3931-ad3a-4887-8aab-12522a22fae7.png)

I am wondering if you have any tips...

Thanks

**Comment by TobiX** [comment]
Ah sorry. The Python wrapper `py` got rewritten for 3.11, which leads to problems in my docker image. Haven't found a fix for this yet. (But `python` should also be on the PATH, so switching py for python should also work...)

**Comment by marcelomanzo** [comment]
Awesome, it works, thanks!
