### ISSUE TITLE
Using pywine to compile Cython

### ISSUE THREAD

**Issue by marcelomanzo** [webcomics/pywine#39]
Hi,

I am trying to compile a cython package using pywine docker image and I am getting the following error:
Error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

I am wondering if is it possible to include c++ build tools as part of the image.

**Comment by marcelomanzo** [comment]
Some info how to install the vs2019 https://bugs.winehq.org/show_bug.cgi?id=47626

**Comment by marcelomanzo** [comment]
How to get an offline package:
https://social.msdn.microsoft.com/Forums/office/en-US/13f2dc59-23e9-459d-b7e6-2a77826f9b5a/standalone-install-of-visual-c-build-tools?forum=vssetup#:~:text=Currently%2C%20there%20is%20not%20a%20standalone%20installer%20of,has%20all%20the%20necessary%20files%20for%20offline%20installation.

**Comment by TobiX** [comment]
After some consideration, I'm not interested in supporting this usecase. If you want to build an image with cython build support, feel free to use my image as a base and I'd be happy to link to it from my README.
