### ISSUE TITLE
Illegal environment variabel name error

### ISSUE THREAD

**Issue by zegervdv** [webcomics/pywine#4]
Thanks for making this image, it was exactly what I was looking for. 

However, when installing the dependencies of my script I’m getting these errors from pip:
~~~
ValueError: Illegal environment variable name
~~~

Installing the requirements.txt on a normal Windows PC does work. 

It can be triggered by adding a package from a git repo (git+https) to your requirements.txt. But I also get it when trying to install iPython.

My guess is some variable is being set by wine but I can’t figure out which one. 
Do you have any ideas how to debug this further?

**Comment by TobiX** [comment]
As far as I can see, the only forbidden character is ` =`:

https://github.com/python/cpython/blob/v3.7.0/Modules/posixmodule.c#L4880-L4883

Sooo, you need to find out how that finds its way into an environment variable name...

**Comment by TobiX** [comment]
It seems  `pip install simplegeneric` provokes the issue...

**Comment by zegervdv** [comment]
It looks like every package that needs to do some kind of subprocess stuff has it. 
Should I open an issue on the pip repo for this?

**Comment by zegervdv** [comment]
I've narrowed it down further to a problem in `subprocess.py` itself.

Trying this on the python.exe prompt (taken from pip/_internal/utils/misc.py lines 644 - 655):
```
>>> import subprocess, os
>>> env = os.environ.copy()
>>> p = subprocess.Popen(['echo', 'hi'], env=env)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
ValueError: illegal environment variable name
```

I don't think it's the `=` that is the issue here. At least if I check each variable for `=` it returns no hits. 
Line 997 of `subprocess.py` references `_winapi.CreateProcess`, but I haven't found the code for that part yet.

**Comment by zegervdv** [comment]
The error seems to be coming from here: https://github.com/python/cpython/blob/c0da582b227f311126e278b5553a7fa89c79b054/Modules/_winapi.c#L761

**Comment by zegervdv** [comment]
There's a second condition to the check: 

```
PyUnicode_GET_LENGTH(key) == 0
```

So searching for zero-length variables gives a hit:
```
>>> for k,v in env.items():
...     if len(k) == 0:
...         print('Found zero length var with value:', v)
...
Found zero length var with value: Z:=Z:\
```
Any idea where it came from? 
It does't show up in `cmd`:
```
Z:\>SET
_=/usr/bin/wine
ALLUSERSPROFILE=C:\users\Public
APPDATA=C:\users\root\Application Data
CLIENTNAME=Console
CommonProgramFiles=C:\Program Files\Common Files
COMPUTERNAME=b1a2cf758340
ComSpec=C:\windows\system32\cmd.exe
DEBIAN_FRONTEND=noninteractive
HOMEDRIVE=C:
HOMEPATH=\users\root
HOSTNAME=b1a2cf758340
LOCALAPPDATA=C:\users\root\Local Settings\Application Data
LOGONSERVER=\\b1a2cf758340
NUMBER_OF_PROCESSORS=1
OS=Windows_NT
PATH=C:Python36-32\Scripts\;C:Python36-32\;C:\windows\system32;C:\windows;C:\windows\system32\wbem
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.PY;.PYW
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_IDENTIFIER=x86 Family 6 Model 62 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3e04
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
PROMPT=$P$G
PYVER=3.6.4
SESSIONNAME=Console
SHLVL=1
SystemDrive=c:
SYSTEMROOT=C:\windows
TEMP=C:\users\root\Temp
TERM=xterm
TINI_VERSION=v0.16.1
TMP=C:\users\root\Temp
USERDOMAIN=b1a2cf758340
USERNAME=root
USERPROFILE=C:\users\root
windir=C:\windows
WINEARCH=win32
WINEDEBUG=-all
WINELOADERNOEXEC=1
WINEPREFIX=/opt/wineprefix
winsysdir=C:\windows\system32

Z:\>
```

**Comment by TobiX** [comment]
I think that's something wine sets?

Nevertheless, this seems like a mis-parse by python: On Windows, environment variables are stored exactly as they are presented: ` key=value` (see [Microsoft Docs](https://docs.microsoft.com/de-de/windows/desktop/ProcThread/environment-variables)), so this variable's name is `Z:` and its value is `Z:\`. It seems to be something like the current working directory?!?

**Comment by zegervdv** [comment]
I’m guessing the `:` is throwing python off somehow. 
Although, from the output of the `SET` command, it doesn’t seem like it is set. 

Interestingly, it does work when starting python directly like this:
```
$ wine python -c ‘import os; print(os.environ[“”]))’
```

**Comment by zegervdv** [comment]
It seems something wine related indeed, see 
https://stackoverflow.com/questions/52003154/python-3-5-5-running-under-wine-sets-environment-variable-with-empty-string-name
But the variable is only set in some circumstances.
Using the `cmd` commanline to run python does not work:
```
$ wine cmd
Z:\>python -m pip install ipython
```

But running it directly does work:
```
$ wine python -m pip install ipython
```

Pipenv does not work in any case. 

But I can work around this for now.

I hope this can be helpful to anyone else running into the same problem.
