### ISSUE TITLE
Latest commit broke pyinstaller compiled exe

### ISSUE THREAD

**Issue by simracingstudio** [webcomics/pywine#58]
Hi, 

I am using the 3.12 version, and the latest commit broke the pyinstaller, everytime I try to load my application I am getting the following error:

![image](https://github.com/webcomics/pywine/assets/47185130/bb6dcd64-2102-456c-be00-f453c7541159)

**Comment by simracingstudio** [comment]
I believe it was the python upgrade to 3.12.4

Is there a way I could force 3.12.3? I am using this docker image with gitlab ci

**Comment by TobiX** [comment]
I pushed an extra image with Python 3.12.3: [`docker.io/tobix/pywine:3.12.3`](https://hub.docker.com/r/tobix/pywine/tags) - please check if that helps (will probably delete this later if I find a fix)

**Comment by TobiX** [comment]
Are you sure this is a problem with my container? This sounds like a known PyInstaller issue (but should be fixed): https://github.com/pyinstaller/pyinstaller/issues/8554

**Comment by simracingstudio** [comment]
@TobiX I was able to fix it, by tweaking the pip dependencies of my application. I really appreciate the effort to spin up a separated version.

Closing now.
