### ISSUE TITLE
wine hangs

### ISSUE THREAD

**Issue by SMUEric1127** [webcomics/pywine#67]
Hi, thank you for making this image, I'm trying to run a python script that requires dll file so I pull the image and used it. However, wine just hang when I do wine python --version

```
root@30ccaee1fe1c:/app# wine --version
wine-9.17
root@30ccaee1fe1c:/app# wine python --version
```

Do you have any idea? Thank you

**Comment by TobiX** [comment]
I cannot reproduce this:
```
root@caf9e57b29e4:/# wine --version
wine-9.17
root@caf9e57b29e4:/# wine python --version
Python 3.12.7
```

**Comment by TobiX** [comment]
I'm closing this for now. Feel free to reopen if you have some new insights, which might help me reproduce the problem.

**Comment by TobiX** [comment]
You might want to try with the latest version, I just updated the container to Python 3.13.0
