### ISSUE TITLE
Trying to rebuild image throws "Application could not be started, or no application associated with the specified file"

### ISSUE THREAD

**Issue by mvccogo** [webcomics/pywine#68]
Greetings,

Due to security restrictions, I need to rebuild the `pywine` image locally using only verified local repositories that provide debian/python packages and the python executable. I managed to successfully install winehq-stable, but after running init-wine.sh and attempting to install the Python executable, the following message appears:

``` dockerfile
ARG PYTHON_VERSION=3.13.0
# Install python 3.12 within wine
RUN umask 0 && cd /tmp/helper && curl -LO \
    https://my.secret.repo/python-$PYTHON_VERSION-amd64.exe && \
    xvfb-run sh -c "\
        wine python-${PYTHON_VERSION}-amd64.exe /quiet /passive TargetDir=C:\\Python \
        Include_doc=0 InstallAllUsers=1 PrependPath=1; \
    wineserver -w"
 ```

> #16 2.349 Application could not be started, or no application associated with the specified file.
> #16 2.349 ShellExecuteEx failed: File not found.

The rest of my dockerfile is omitted here but is practically a 1:1 copy of `pywine` and `wine-docker`.
Running `wine start /unix` gets rid of the error, but the command hangs.

**Comment by TobiX** [comment]
Are you sure the installer file isn't corrupted? You might want to add `--fail-with-body` to the curl call if you aren't verifying the integrity of the download afterwards...

**Comment by mvccogo** [comment]
Hello! Completely forgot to update this issue. You were dead right, curl was failing the authentication. Fixing that has solved the issue. Happy 2025, and thanks!
